// Shared data model for the Ideabro server and web client.

export type AssetKind =
  | 'creator'
  | 'product'
  | 'environment'
  | 'logo'
  | 'props'
  | 'narrator'
  | 'music'
  | 'sfx'
  | 'other';

export const VISUAL_ASSET_KINDS: AssetKind[] = ['creator', 'product', 'environment', 'logo', 'props', 'narrator', 'other'];
export const AUDIO_ASSET_KINDS: AssetKind[] = ['music', 'sfx'];

export interface Asset {
  id: string;
  /** Tag used in the idea/script without the leading "@", e.g. "creator", "product", "maya". */
  tag: string;
  kind: AssetKind;
  name: string;
  description: string;
  /** Uploaded file, served by the Ideabro server. */
  file?: { path: string; url: string; mime: string; originalName: string; size: number };
  /** Optional publicly reachable URL (CDN/S3). Used as the reference sent to APIMart when present. */
  remoteUrl?: string;
  createdAt: string;
}

export type PlatformId =
  | 'tiktok'
  | 'reels'
  | 'shorts'
  | 'youtube'
  | 'instagram-feed'
  | 'facebook-feed'
  | 'linkedin';

export interface Platform {
  id: PlatformId;
  label: string;
  /** Aspect ratio of the final export. */
  aspect: '9:16' | '16:9' | '1:1' | '4:5';
  width: number;
  height: number;
}

export type VideoFormat = 'ugc' | 'ad' | 'campaign' | 'film';

export interface Brief {
  idea: string;
  durationSec: number;
  platform: PlatformId;
  language: string;
  format: VideoFormat;
  tone: string;
  brandName: string;
  cta: string;
  /** Maximum length of a single generated clip (Omni 1.1 Flash tops out at 10s). */
  maxClipSec: number;
  /** Omni output resolution (also sets APIMart's cost tier). */
  resolution: Resolution;
  /**
   * How clip N continues from clip N-1:
   *  - reference: send clip N-1 as `video_urls` (needs a public URL for the clip)
   *  - extend:    send `extend_from_task_id` = clip N-1's APIMart task (no URL needed)
   */
  continuity: ContinuityMode;
}

export type Resolution = '360p' | '720p' | '1080p' | '4k';
export const RESOLUTIONS: Resolution[] = ['360p', '720p', '1080p', '4k'];
export type ContinuityMode = 'reference' | 'extend';

export interface Concept {
  id: string;
  title: string;
  hook: string;
  angle: string;
  summary: string;
}

export type Beat = 'hook' | 'problem' | 'solution' | 'demo' | 'benefit' | 'social-proof' | 'offer' | 'cta' | 'story' | 'other';

export interface Scene {
  id: string;
  index: number;
  durationSec: number;
  beat: Beat;
  /** Where the scene happens. */
  setting: string;
  /** Camera framing / movement. */
  camera: string;
  /** What happens on screen. */
  action: string;
  /** Spoken line(s) for this scene, in the brief's language. */
  dialogue: string;
  /** Who speaks: an @tag (e.g. "@creator") or "narrator (voice-over)". */
  speaker: string;
  /** Asset tags (without "@") that appear in the scene. */
  assetTags: string[];
  /** For scenes after the first: what changes relative to the previous clip (angle, environment, new person...). */
  changes: string;
  /** Optional sound design notes; also used as a hint for SFX placement. */
  sfx: string;
}

export interface CastNote {
  /** Tag without "@". */
  tag: string;
  kind: AssetKind;
  /** Rich visual/voice description. Generated by AI when the user did not supply an asset. */
  description: string;
  generated: boolean;
}

export interface Script {
  title: string;
  logline: string;
  voiceStyle: string;
  musicMood: string;
  visualStyle: string;
  cast: CastNote[];
  scenes: Scene[];
  endCard: { headline: string; cta: string };
}

export type ClipStatus = 'idle' | 'queued' | 'submitting' | 'generating' | 'downloading' | 'ready' | 'failed';

export interface ClipVersion {
  version: number;
  prompt: string;
  url: string;
  localPath: string;
  remoteUrl?: string;
  /** Unix seconds after which APIMart's remoteUrl stops working. */
  remoteExpiresAt?: number;
  /** APIMart task that produced this take (used for extend_from_task_id). */
  taskId?: string;
  /** Seconds cut from the start (an "extend" result can include the previous clip). */
  trimStart?: number;
  createdAt: string;
}

export interface Clip {
  id: string;
  sceneId: string;
  index: number;
  durationSec: number;
  prompt: string;
  /** Use the previous clip's video as the reference for continuity (ignored for the first clip). */
  useVideoRef: boolean;
  /** Asset ids sent as reference images. */
  imageAssetIds: string[];
  status: ClipStatus;
  progress: number;
  taskId?: string;
  error?: string;
  /** URL of the generated video as returned by APIMart (used as the next clip's video reference). */
  remoteUrl?: string;
  localPath?: string;
  url?: string;
  version: number;
  history: ClipVersion[];
  /** True when an upstream clip changed after this clip was generated, so continuity may be broken. */
  stale: boolean;
  /** The previous clip's version this clip was generated from (continuity tracking). */
  basedOnPrevVersion?: number;
  trimStart: number;
  trimEnd: number;
  /** Caption text override; defaults to the scene dialogue. */
  captionText?: string;
}

export type CaptionStyle = 'bold' | 'clean' | 'karaoke';
export type Corner = 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right';

export interface SfxCue {
  id: string;
  assetId: string;
  atSec: number;
  volume: number;
}

export interface EditSettings {
  transition: { type: 'cut' | 'fade' | 'crossfade'; durationSec: number };
  captions: {
    enabled: boolean;
    style: CaptionStyle;
    position: 'bottom' | 'middle' | 'top';
    uppercase: boolean;
    wordsPerLine: number;
    fontSize: number;
    highlightColor: string;
  };
  voiceVolume: number;
  music: { assetId?: string; volume: number; duck: boolean; fadeOutSec: number };
  sfx: SfxCue[];
  logo: { enabled: boolean; assetId?: string; position: Corner; scale: number; opacity: number };
  endCard: {
    enabled: boolean;
    durationSec: number;
    headline: string;
    cta: string;
    bgColor: string;
    textColor: string;
    logoAssetId?: string;
  };
}

export interface RenderState {
  status: 'idle' | 'rendering' | 'done' | 'failed';
  progress: number;
  step?: string;
  error?: string;
  url?: string;
  durationSec?: number;
  updatedAt?: string;
  history: { url: string; createdAt: string; durationSec?: number }[];
}

export type Stage = 'brief' | 'concept' | 'script' | 'prompts' | 'generate' | 'edit' | 'export';
export const STAGES: Stage[] = ['brief', 'concept', 'script', 'prompts', 'generate', 'edit', 'export'];

export interface AutopilotState {
  running: boolean;
  step?: string;
  error?: string;
}

export interface Project {
  id: string;
  name: string;
  createdAt: string;
  updatedAt: string;
  stage: Stage;
  brief: Brief;
  assets: Asset[];
  concepts: Concept[];
  selectedConceptId?: string;
  script?: Script;
  clips: Clip[];
  generating: boolean;
  edit: EditSettings;
  render: RenderState;
  autopilot: AutopilotState;
}

export interface AppConfig {
  mockVideo: boolean;
  mockLlm: boolean;
  videoModel: string;
  llmModel: string;
  maxImageRefs: number;
  maxClipSec: number;
  minClipSec: number;
  publicBaseUrl?: string;
  xfade: boolean;
  platforms: Platform[];
  languages: string[];
}

export const PLATFORMS: Platform[] = [
  { id: 'tiktok', label: 'TikTok', aspect: '9:16', width: 1080, height: 1920 },
  { id: 'reels', label: 'Instagram Reels', aspect: '9:16', width: 1080, height: 1920 },
  { id: 'shorts', label: 'YouTube Shorts', aspect: '9:16', width: 1080, height: 1920 },
  { id: 'youtube', label: 'YouTube (landscape)', aspect: '16:9', width: 1920, height: 1080 },
  { id: 'instagram-feed', label: 'Instagram Feed (4:5)', aspect: '4:5', width: 1080, height: 1350 },
  { id: 'facebook-feed', label: 'Facebook Feed (1:1)', aspect: '1:1', width: 1080, height: 1080 },
  { id: 'linkedin', label: 'LinkedIn (1:1)', aspect: '1:1', width: 1080, height: 1080 },
];

export const LANGUAGES = [
  'English',
  'Hindi',
  'Hinglish',
  'Spanish',
  'Portuguese',
  'French',
  'German',
  'Italian',
  'Arabic',
  'Indonesian',
  'Japanese',
  'Korean',
  'Turkish',
  'Tamil',
  'Telugu',
  'Marathi',
  'Bengali',
];

export function platformById(id: PlatformId): Platform {
  return PLATFORMS.find((p) => p.id === id) ?? PLATFORMS[0];
}

/** Split a target duration into clip lengths within [minSec, maxSec], as evenly as possible. */
export function splitDuration(totalSec: number, maxSec = 10, minSec = 3): number[] {
  const total = Math.max(minSec, Math.round(totalSec));
  const count = Math.max(1, Math.ceil(total / maxSec));
  const base = Math.floor(total / count);
  const rest = total - base * count;
  return Array.from({ length: count }, (_, i) => Math.max(minSec, Math.min(maxSec, base + (i < rest ? 1 : 0))));
}
